[ClassVersion("1.0.0"), FriendlyName("xCreateShortcut")]
class MSFT_xCreateShortcut: OMI_BaseResource
{
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Key] string ShortcutName;
  [Key] string ShortcutPath;
  [Key] string TargetPath;
};