[ClassVersion("1.0.0"), FriendlyName("CreateShortcut")]
class CreateShortcut: OMI_BaseResource
{
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Key] string ShortcutName;
  [Key] string ShortcutPath;
  [Key] string TargetPath;
};